### ISSUE TITLE
Lamp doesn't break when switch turned off

### ISSUE THREAD

**Issue by Jhsteensma** [wzwietering/IntroductieProject#43]
In a circuit where a lightbulb and a turned off switch are connected in serie, when the run button is pressed the light turns on where it should have broken. If the switch is turned on and the run is pressed, the lamp breaks.

**Comment by wzwietering** [comment]
Do you mean a circuit like this one? 
![screenshot_1484059631](https://cloud.githubusercontent.com/assets/15837844/21810488/548b5d5c-d74c-11e6-9487-efae978320ae.png)

**Comment by Jhsteensma** [comment]
yes, in my app the light would turn on and not break down.

**Comment by wzwietering** [comment]
This seems to be the fix, since I cannot reproduce the bug in this branch: https://github.com/wzwietering/IntroductieProject/pull/46
