### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by Jhsteensma** [wzwietering/IntroductieProject#50]
Main screen starts with dutch language and english flag. 
When flag is pressed language stays dutch and flag becomes dutch
Afterwards works fine.

**Comment by wzwietering** [comment]
This should be fixed, however, I have not tested this on a Dutch phone, so I will verify it

**Comment by wzwietering** [comment]
Okay, so on an English phone it works, but on a Dutch one not. I will fix this issues, thanks for finding it

**Comment by wzwietering** [comment]
Fixed: https://github.com/wzwietering/IntroductieProject/pull/55
