### ISSUE TITLE
The menus are ugly when using a tablet

### ISSUE THREAD

**Issue by wzwietering** [wzwietering/IntroductieProject#56]
![screenshot_1484493363](https://cloud.githubusercontent.com/assets/15837844/21963809/e735cb9a-db40-11e6-9516-6978a3e7970f.png)
![screenshot_1484493358](https://cloud.githubusercontent.com/assets/15837844/21963810/e81ffd50-db40-11e6-9331-43f13eaa33b2.png)

**Comment by bvdhoek** [comment]
Fixed 👍
