### ISSUE TITLE
Animation doesn't turn red

### ISSUE THREAD

**Issue by bvdhoek** [wzwietering/IntroductieProject#72]

**Comment by bvdhoek** [comment]
![circuit-broken](https://cloud.githubusercontent.com/assets/19154653/22152090/897d5ede-df21-11e6-9c39-77ac0406dbb4.png)

**Comment by bvdhoek** [comment]
zijn niet rood dat zijn paint skills

**Comment by wzwietering** [comment]
Reproduction in current master shows that this issue is solved.  ![screenshot_1485292889](https://cloud.githubusercontent.com/assets/15837844/22267263/78c8a3d6-e283-11e6-8777-afcede66d2a5.png)
